- hosts: app
  gather_facts: no
  vars:
    image: auth
    registry: docker.pkg.github.com
    repository: '{{ registry }}/ilukashin/tn_micro_auth/{{ image }}'
  tasks:
    - name: build docker image
      delegate_to: 127.0.0.1
      docker_image:
        build:
          path: ../
          pull: no
        name: '{{ image }}'
        source: build
        force_source: yes
    - name: login to docker registry
      delegate_to: 127.0.0.1
      docker_login:
        registry: '{{ registry }}'
        username: deploy
        password: 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

    - name: push image
      delegate_to: 127.0.0.1
      docker_image:
        name: '{{ image }}'
        repository: '{{ repository }}'
        push: yes
        source: local
        force_tag: yes
    - name: login to docker registry on remote
      become: yes
      docker_login:
        registry: '{{ registry }}'
        # username: '{{ lookup("env", "DOCKER_USER") }}'
        # password: '{{ lookup("env", "DOCKER_PASSWORD") }}'
        username: deploy
        password: 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
    - name: pull image on remote
      become: yes
      docker_image:
        name: '{{ repository }}'
        source: pull
        force_source: yes
    - name: run database migrations
      become: yes
      run_once: yes
      docker_container:
        name: auth-migrations
        image: '{{ repository }}'
        network_mode: host
        detach: no
        cleanup: yes
        command: bin/rake db:migrate
        env_file: '/home/{{ ansible_user }}/.env'

    - name: run app container 
      become: yes
      docker_container:
        name: auth-service
        image: '{{ repository }}'
        ports:
          - "3010:3010"
        network_mode: host
        detach: no
        # link log inside container to host directory volume
        volumes:
          - /var/log:/var/log/app.log:ro
        command: bin/puma -p 3010
        env_file: '/home/{{ ansible_user }}/.env'
        restart_policy: on-failure
        restart_retries: 10
        state: started
