db:
  adapter: postgresql
  host: localhost
  user: postgres
  url: <%= ENV['AUTH_DATABASE_URL'] %>
pagination:
  page_size: 10
app:
  name: auth
  secret: secret

rabbitmq:
  consumer_pool: 10
  
logger:
  path: log/app.log
  level: info
